name: Mirror Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - image: alpine
            repo: docker.io
          - image: busybox
            repo: docker.io
          - image: debian
            repo: docker.io
          - image: golang
            repo: docker.io
          - image: mysql
            repo: docker.io
          - image: node
            repo: docker.io
          - image: openjdk
            repo: docker.io
          - image: postgres
            repo: docker.io
          - image: python
            repo: docker.io
          - image: rust
            repo: docker.io
          - image: ubuntu
            repo: docker.io
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: actions/setup-go@v5
      - uses: imjasonh/setup-crane@v0.3
      - name: Mirror
        run: |
          copied_tags=""
          failed_tags=""
          for tag in $(crane ls ${{ matrix.repo }}/${{ matrix.image }}); do
            if crane validate --remote ${{ matrix.image }}:$tag; then
              echo "Tag $tag is valid, mirroring..."
              if crane copy ${{ matrix.repo }}/${{ matrix.image }}:$tag ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:$tag; then
                echo "Successfully mirrored tag: $tag"
                copied_tags="$copied_tags $tag"
              else
                echo "Failed to mirror tag: $tag"
                failed_tags="$failed_tags $tag"
              fi
            else
              echo "Skipping invalid tag: $tag"
              failed_tags="$failed_tags $tag"
            fi
          done

          # Output copied tags and failed tags
          echo "Copied tags: $copied_tags"
            echo "Failed tags: $failed_tags"
