name: Update Image Versions

on:
  workflow_dispatch:
  schedule:
    - cron: "50 23 * * *" # Run daily

jobs:
  update_versions:
    name: Update Versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: actions/setup-go@v5
      - uses: imjasonh/setup-crane@v0.3
      - name: Check for newer versions and update files
        run: |
          # Loop through each image file
          for image_file in ./images/*; do
            image=$(basename "$image_file")
            latest_version=$(tail -n 1 "$image_file")
            new_versions=$(crane ls docker.io/"$image" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+(-.*)?$' | sort -V | grep -A 1000 "$latest_version" | grep -v "$latest_version")
          done
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
